### PR TITLE
feat-be: API Gateway

### PR DESCRIPTION
**Pull request by patrykferenc**

### CODE REVIEW

**Comment by patrykferenc** [comment]
I will add docker compose later @LARP2023Z/architects  - I will put it in the root folder and use relative paths to include compose files from other directories. It should be ez to use for the whole team.

**Comment by patrykferenc** [comment]
Also blocked by other BE parts that are missing

**Review by bastyje — DISMISSED** [review]
some ci workflow would be fine

**Comment by patrykferenc** [comment]
> some ci workflow would be fine

I'd do it but there are no tests in the GW aaaaand I don't think we /need/ it

**Review by legeof008 — APPROVED** [review]

**Pull request merged**
